import { Archive, BookOpen, CheckCircle2, FileArchive, Image, LoaderCircle, Pencil } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { FormActions, Loader, Modal, Notice } from "../components/ui";
import { parseCrmCatalogZip } from "../lib/catalogZip";
import { humanError, money } from "../lib/helpers";
import { importCatalogItems, loadCatalog, updateCatalogItem } from "../lib/repository";
import type { CatalogItem } from "../lib/types";

export function CatalogPage({ userId }: { userId: string }) {
  const [items, setItems] = useState<CatalogItem[]>([]); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false);
  const [progress, setProgress] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [editing, setEditing] = useState<CatalogItem | null>(null); const input = useRef<HTMLInputElement>(null);
  async function refresh() { setLoading(true); try { setItems(await loadCatalog()); } catch (reason) { setError(humanError(reason)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  async function importZip(file?: File) { if (!file) return; setPending(true); setError(""); setSuccess(""); try { setProgress("Читаем архив CRM Photo…"); const parsed = await parseCrmCatalogZip(file); setProgress(`Найдено услуг: ${parsed.length}`); const count = await importCatalogItems(userId, parsed, (done, total) => setProgress(`Загружаем услуги и превью: ${done} из ${total}`)); setSuccess(`Каталог импортирован: ${count} услуг. Повторный импорт обновит их без дублей.`); setProgress(""); await refresh(); } catch (reason) { setError(humanError(reason)); setProgress(""); } finally { setPending(false); if (input.current) input.current.value = ""; } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setPending(true); setError(""); const form = new FormData(event.currentTarget); try { await updateCatalogItem(editing.id, { name: String(form.get("name") || "").trim(), short_description: String(form.get("short_description") || "").trim(), description: String(form.get("description") || "").trim(), price: Number(form.get("price") || 0), is_active: form.get("is_active") === "on" }); setEditing(null); setSuccess("Услуга сохранена"); await refresh(); } catch (reason) { setError(humanError(reason)); } finally { setPending(false); } }
  return <div className="page"><header className="page-header"><div><span className="eyebrow">CRM PHOTO</span><h1>Каталог услуг</h1><p>Импортируйте ZIP, экспортированный кнопкой «Публичный каталог» в CRM Photo.</p></div><><input ref={input} className="visually-hidden" type="file" accept=".zip,application/zip" onChange={(event) => void importZip(event.target.files?.[0])}/><button className="button button-primary" disabled={pending} onClick={() => input.current?.click()}>{pending ? <LoaderCircle className="spin" size={18}/> : <FileArchive size={18}/>}Добавить ZIP-каталог</button></></header>
    {error && <Notice kind="error">{error}</Notice>}{success && <Notice>{success}</Notice>}{progress && <Notice kind="info">{progress}</Notice>}
    <div className="import-help"><Archive size={24}/><div><strong>Поддерживаемый архив</strong><span>`catalog_export.zip`: файл `catalog.json`, изображения из `assets/images` и видео из `assets/videos`.</span></div><CheckCircle2 size={22}/></div>
    {loading ? <Loader label="Загружаем каталог…"/> : <div className="catalog-grid">{items.map((item) => <article className={`catalog-card ${!item.is_active ? "card-disabled" : ""}`} key={item.id}><div className="catalog-preview">{item.preview_url ? <img src={item.preview_url} alt=""/> : <Image size={36}/>}<span>{item.type}</span></div><div className="catalog-body"><div className="catalog-title"><h2>{item.name}</h2><strong>{money(item.price)}</strong></div><p>{item.short_description || item.description || "Описание не добавлено"}</p><div className="catalog-footer"><span className="source-label">{item.source === "crm_photo_zip" ? "CRM Photo ZIP" : "Базовый каталог"}</span><button className="icon-button" onClick={() => setEditing(item)} aria-label="Изменить"><Pencil size={17}/></button></div></div></article>)}</div>}
    {!loading && !items.length && <div className="empty-state"><BookOpen/><h3>Каталог пуст</h3><p>Добавьте ZIP-файл из CRM Photo.</p></div>}
    {editing && <Modal title="Изменить услугу" onClose={() => setEditing(null)}><form className="form-stack" onSubmit={save}><label>Название *<input name="name" required defaultValue={editing.name}/></label><label>Краткое описание<input name="short_description" defaultValue={editing.short_description}/></label><label>Полное описание<textarea name="description" rows={4} defaultValue={editing.description}/></label><label>Цена, ₽<input name="price" type="number" min="0" step="1" defaultValue={editing.price}/></label><label className="checkbox-row"><input name="is_active" type="checkbox" defaultChecked={editing.is_active}/>Показывать родителям</label><FormActions pending={pending} submitLabel="Сохранить" onCancel={() => setEditing(null)}/></form></Modal>}
  </div>;
}
