import { BookOpen, FileArchive, Image, LoaderCircle, Pencil, Settings2, Trash2, Video } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { FormActions, Loader, Modal, Notice } from "../components/ui";
import { parseCrmCatalogZip } from "../lib/catalogZip";
import { humanError, money } from "../lib/helpers";
import { importCatalogItems, loadCatalog, updateCatalogItem } from "../lib/repository";
import type { CatalogItem } from "../lib/types";

type Watermark = { text: string; image: string; opacity: number };
const defaultWatermark: Watermark = { text: "", image: "", opacity: 0.55 };
function readWatermark(): Watermark { try { return { ...defaultWatermark, ...JSON.parse(localStorage.getItem("vakha-watermark") || "{}") }; } catch { return defaultWatermark; } }

export function CatalogPage({ userId }: { userId: string }) {
  const [items, setItems] = useState<CatalogItem[]>([]); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false);
  const [progress, setProgress] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [editing, setEditing] = useState<CatalogItem | null>(null); const [preview, setPreview] = useState<CatalogItem | null>(null); const [settingsOpen, setSettingsOpen] = useState(false);
  const [watermark, setWatermark] = useState<Watermark>(readWatermark); const input = useRef<HTMLInputElement>(null); const watermarkInput = useRef<HTMLInputElement>(null);
  async function refresh() { setLoading(true); try { setItems(await loadCatalog()); } catch (reason) { setError(humanError(reason)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  async function importZip(file?: File) { if (!file) return; setPending(true); setError(""); setSuccess(""); try { setProgress("Читаем архив…"); const parsed = await parseCrmCatalogZip(file); const count = await importCatalogItems(userId, parsed, (done, total) => setProgress(`Импорт ${done} из ${total}`)); setSuccess(`Импортировано услуг: ${count}`); setProgress(""); await refresh(); } catch (reason) { setError(humanError(reason)); setProgress(""); } finally { setPending(false); if (input.current) input.current.value = ""; } }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setPending(true); setError(""); const form = new FormData(event.currentTarget); try { await updateCatalogItem(editing.id, { name: String(form.get("name") || "").trim(), short_description: String(form.get("short_description") || "").trim(), description: String(form.get("description") || "").trim(), price: Number(form.get("price") || 0), is_active: form.get("is_active") === "on" }); setEditing(null); setSuccess("Сохранено"); await refresh(); } catch (reason) { setError(humanError(reason)); } finally { setPending(false); } }
  function saveWatermark(next: Watermark) { setWatermark(next); localStorage.setItem("vakha-watermark", JSON.stringify(next)); }
  function readWatermarkFile(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => saveWatermark({ ...watermark, image: String(reader.result || "") }); reader.readAsDataURL(file); }
  function watermarkLayer() { return <>{watermark.image && <img className="watermark-image" style={{ opacity: watermark.opacity }} src={watermark.image} alt=""/>}{watermark.text && <span className="watermark-text" style={{ opacity: watermark.opacity }}>{watermark.text}</span>}</>; }
  return <div className="page"><header className="page-header"><div><span className="eyebrow">CRM PHOTO</span><h1>Каталог</h1></div><div className="inline-actions"><button className="button button-secondary" onClick={() => setSettingsOpen(true)}><Settings2 size={18}/>Водяной знак</button><input ref={input} className="visually-hidden" type="file" accept=".zip,application/zip" onChange={(event) => void importZip(event.target.files?.[0])}/><button className="button button-primary" disabled={pending} onClick={() => input.current?.click()}>{pending ? <LoaderCircle className="spin" size={18}/> : <FileArchive size={18}/>} {pending ? "Импорт…" : "Импортировать ZIP"}</button></div></header>
    {error && <Notice kind="error">{error}</Notice>}{success && <Notice>{success}</Notice>}{progress && <Notice kind="info">{progress}</Notice>}
    {loading ? <Loader label="Загружаем…"/> : <div className="catalog-grid">{items.map((item) => <article className={`catalog-card ${!item.is_active ? "card-disabled" : ""}`} key={item.id} onClick={() => setPreview(item)}><div className="catalog-preview">{item.preview_url ? <img src={item.preview_url} alt=""/> : <Image size={36}/>}<div className="catalog-watermark">{watermarkLayer()}</div>{item.preview_video_url && <span className="media-badge">Видео</span>}<span className="catalog-type">{item.type}</span></div><div className="catalog-body"><div className="catalog-title"><h2>{item.name}</h2><strong>{money(item.price)}</strong></div><p>{item.short_description || item.description || "Без описания"}</p><div className="catalog-footer"><span className="source-label">{item.source === "crm_photo_zip" ? "CRM Photo" : "Базовый"}</span><button className="icon-button" onClick={(event) => { event.stopPropagation(); setEditing(item); }} aria-label="Изменить"><Pencil size={17}/></button></div></div></article>)}</div>}
    {!loading && !items.length && <div className="empty-state"><BookOpen/><h3>Каталог пуст</h3><p>Импортируйте ZIP из CRM Photo.</p></div>}
    {preview && <Modal title={preview.name} onClose={() => setPreview(null)}><div className="catalog-viewer">{preview.preview_video_url ? <video controls playsInline poster={preview.preview_url || undefined} src={preview.preview_video_url}/> : preview.preview_url ? <img src={preview.preview_url} alt={preview.name}/> : <Image size={64}/>}<div className="catalog-watermark">{watermarkLayer()}</div></div><div className="viewer-meta"><strong>{money(preview.price)}</strong><span>{preview.description || preview.short_description || ""}</span></div></Modal>}
    {settingsOpen && <Modal title="Водяной знак" onClose={() => setSettingsOpen(false)}><div className="watermark-settings"><p className="settings-hint">Показывается поверх превью каталога.</p><label>Текст<input value={watermark.text} onChange={(event) => saveWatermark({ ...watermark, text: event.target.value })} placeholder="Vakha Studio"/></label><input ref={watermarkInput} className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => readWatermarkFile(event.target.files?.[0])}/><button className="button button-secondary" onClick={() => watermarkInput.current?.click()}><Image size={18}/>Загрузить логотип</button>{watermark.image && <div className="watermark-file"><img src={watermark.image} alt=""/><button className="icon-button danger-icon" onClick={() => saveWatermark({ ...watermark, image: "" })}><Trash2 size={16}/></button></div>}<label>Прозрачность<input type="range" min="0.1" max="1" step="0.05" value={watermark.opacity} onChange={(event) => saveWatermark({ ...watermark, opacity: Number(event.target.value) })}/></label></div></Modal>}
    {editing && <Modal title="Изменить услугу" onClose={() => setEditing(null)}><form className="form-stack" onSubmit={save}><label>Название *<input name="name" required defaultValue={editing.name}/></label><label>Краткое описание<input name="short_description" defaultValue={editing.short_description}/></label><label>Полное описание<textarea name="description" rows={4} defaultValue={editing.description}/></label><label>Цена, ₽<input name="price" type="number" min="0" step="1" defaultValue={editing.price}/></label><label className="checkbox-row"><input name="is_active" type="checkbox" defaultChecked={editing.is_active}/>Показывать родителям</label><FormActions pending={pending} submitLabel="Сохранить" onCancel={() => setEditing(null)}/></form></Modal>}
  </div>;
}
