import { ArrowLeft, Check, Clipboard, Download, FileSpreadsheet, Link2, Pencil, Send, Trash2, UserPlus, Users } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { QRCodeSVG } from "qrcode.react";
import { EmptyState, FormActions, Loader, Modal, Notice } from "../components/ui";
import { parseChildrenFile } from "../lib/childrenImport";
import { downloadCsv, formatDateTime, humanError, orderStatusLabels } from "../lib/helpers";
import { createChild, importChildren, loadClass, updateChild } from "../lib/repository";
import type { Child, ParentOrder, School, SchoolClass } from "../lib/types";

export function ClassPage() {
  const { classId = "" } = useParams();
  const [schoolClass, setSchoolClass] = useState<SchoolClass | null>(null); const [school, setSchool] = useState<School | null>(null);
  const [children, setChildren] = useState<Child[]>([]); const [orders, setOrders] = useState<ParentOrder[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [childModal, setChildModal] = useState<Child | null | undefined>(undefined); const [pending, setPending] = useState(false);
  const importRef = useRef<HTMLInputElement>(null); const [copied, setCopied] = useState(false);
  async function refresh() { setLoading(true); try { const data = await loadClass(classId); setSchoolClass(data.schoolClass); setSchool(data.school); setChildren(data.children); setOrders(data.orders); } catch (reason) { setError(humanError(reason)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [classId]);
  const publicUrl = schoolClass ? `${window.location.origin}/p/${schoolClass.public_token}` : "";
  async function submitChild(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const draft = { first_name: String(form.get("first_name") || "").trim(), last_name: String(form.get("last_name") || "").trim(), public_name: String(form.get("public_name") || "").trim() }; try { if (childModal) await updateChild(childModal.id, draft); else await createChild(classId, draft); setChildModal(undefined); setSuccess(childModal ? "Данные ребёнка обновлены" : "Ребёнок добавлен"); await refresh(); } catch (reason) { setError(humanError(reason)); } finally { setPending(false); } }
  async function archiveChild(child: Child) { if (!window.confirm(`Убрать ${child.public_name} из активного списка?`)) return; try { await updateChild(child.id, { status: "archived" }); setSuccess("Ребёнок перемещён в архив"); await refresh(); } catch (reason) { setError(humanError(reason)); } }
  async function handleImport(file?: File) { if (!file) return; setPending(true); setError(""); setSuccess(""); try { const rows = await parseChildrenFile(file); const result = await importChildren(classId, rows); setSuccess(`Импорт завершён: добавлено ${result.added}, пропущено дублей ${result.skipped}`); await refresh(); } catch (reason) { setError(humanError(reason)); } finally { setPending(false); if (importRef.current) importRef.current.value = ""; } }
  async function copyLink() { await navigator.clipboard.writeText(publicUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  async function shareLink() { const text = `${school?.name}, класс ${schoolClass?.name}. Выберите ребёнка и услуги: ${publicUrl}`; if (navigator.share) await navigator.share({ title: "Ссылка для родителей", text, url: publicUrl }); else window.location.href = `mailto:?subject=${encodeURIComponent("Ссылка для родителей")}&body=${encodeURIComponent(text)}`; }
  function exportOrders() { const byChild = new Map(children.map((item) => [item.id, item])); const rows: unknown[][] = [["Школа", "Класс", "Ребёнок", "Номер заявки", "Выбранные услуги", "Сумма", "Статус", "Дата заявки", "Комментарий"]]; orders.forEach((order) => rows.push([school?.name, schoolClass?.name, byChild.get(order.child_id)?.public_name || "", order.order_number, order.selected_items.map((item) => item.name).join(", "), order.total_amount, orderStatusLabels[order.status], formatDateTime(order.created_at), order.parent_note])); downloadCsv(`${school?.name}_${schoolClass?.name}_заявки.csv`, rows); }
  if (loading) return <div className="page"><Loader label="Загружаем класс…"/></div>;
  if (!schoolClass || !school) return <div className="page"><Notice kind="error">Класс не найден</Notice></div>;
  const orderedChildIds = new Set(orders.filter((order) => order.status !== "cancelled").map((order) => order.child_id));
  return <div className="page"><Link className="back-link" to={`/admin/schools/${school.id}`}><ArrowLeft size={17}/>{school.name}</Link>
    <header className="page-header"><div><span className="eyebrow">{school.name} · {schoolClass.academic_year}</span><h1>Класс {schoolClass.name}</h1><p>{schoolClass.teacher_name || "Классный руководитель не указан"}</p></div><button className="button button-secondary" onClick={exportOrders} disabled={!orders.length}><Download size={18}/>Экспорт заявок</button></header>
    {error && <Notice kind="error">{error}</Notice>}{success && <Notice>{success}</Notice>}
    <div className="metric-grid"><div className="metric"><span>Детей</span><strong>{children.length}</strong></div><div className="metric"><span>Заявок</span><strong>{orders.filter((o) => o.status !== "cancelled").length}</strong></div><div className="metric metric-warning"><span>Без заявки</span><strong>{children.filter((c) => !orderedChildIds.has(c.id)).length}</strong></div></div>
    <section className="share-card"><div className="share-copy"><span className="eyebrow">ССЫЛКА ДЛЯ РОДИТЕЛЕЙ</span><h2>Класс готов к приёму заявок</h2><p>Передайте ссылку классному руководителю. Родители увидят только публичные имена.</p><div className="public-url"><Link2 size={19}/><span>{publicUrl}</span></div><div className="inline-actions"><button className="button button-primary" onClick={() => void copyLink()}>{copied ? <Check size={18}/> : <Clipboard size={18}/>} {copied ? "Скопировано" : "Копировать ссылку"}</button><button className="button button-secondary" onClick={() => void shareLink()}><Send size={18}/>Отправить учителю</button></div></div><div className="qr-box"><QRCodeSVG value={publicUrl} size={148} level="M"/><small>Наведите камеру</small></div></section>
    <section className="section-card"><div className="section-title"><div><h2>Дети</h2><p>Полные имена доступны только администратору</p></div><div className="inline-actions"><input ref={importRef} className="visually-hidden" type="file" accept=".csv,.xlsx,.xls" onChange={(e) => void handleImport(e.target.files?.[0])}/><button className="button button-secondary" disabled={pending} onClick={() => importRef.current?.click()}><FileSpreadsheet size={18}/>Импорт CSV / Excel</button><button className="button button-primary" onClick={() => setChildModal(null)}><UserPlus size={18}/>Добавить ребёнка</button></div></div>
      {children.length === 0 ? <EmptyState icon={<Users/>} title="Список детей пуст" text="Добавьте ребёнка вручную или импортируйте таблицу."/> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Ребёнок</th><th>Публичное имя</th><th>Заявка</th><th aria-label="Действия"/></tr></thead><tbody>{children.map((child) => <tr key={child.id}><td><strong>{child.last_name} {child.first_name}</strong></td><td>{child.public_name}</td><td>{orderedChildIds.has(child.id) ? <span className="status status-ready">Получена</span> : <span className="status status-new">Нет заявки</span>}</td><td className="row-actions"><button className="icon-button" title="Изменить" onClick={() => setChildModal(child)}><Pencil size={17}/></button><button className="icon-button danger-icon" title="Архивировать" onClick={() => void archiveChild(child)}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>}
    </section>
    {childModal !== undefined && <Modal title={childModal ? "Изменить ребёнка" : "Добавить ребёнка"} onClose={() => setChildModal(undefined)}><form className="form-stack" onSubmit={submitChild}><div className="form-grid"><label>Имя *<input name="first_name" required defaultValue={childModal?.first_name || ""} placeholder="Адам"/></label><label>Фамилия *<input name="last_name" required defaultValue={childModal?.last_name || ""} placeholder="Абдуллаев"/></label></div><label>Публичное имя<input name="public_name" defaultValue={childModal?.public_name || ""} placeholder="Автоматически: Адам А."/><small>Родители увидят только это имя</small></label><FormActions pending={pending} submitLabel={childModal ? "Сохранить" : "Добавить"} onCancel={() => setChildModal(undefined)}/></form></Modal>}
  </div>;
}
