import { ArrowLeft, Camera, Check, CheckCircle2, Image, LoaderCircle, Play, UserRound, Video } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { Loader, Notice } from "../components/ui";
import { humanError, money } from "../lib/helpers";
import { getPublicClass, submitPublicOrder } from "../lib/repository";
import type { PublicClassPayload, PublicOrderResult } from "../lib/types";

type Step = "child" | "services" | "done";

function ServiceIcon({ type }: { type: string }) { if (type === "video") return <Video/>; if (type === "interview") return <Play/>; if (type === "ai") return <UserRound/>; return <Camera/>; }

export function PublicOrderPage() {
  const { token = "" } = useParams(); const [data, setData] = useState<PublicClassPayload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [step, setStep] = useState<Step>("child");
  const [childId, setChildId] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [pending, setPending] = useState(false); const [result, setResult] = useState<PublicOrderResult | null>(null); const requestKey = useRef(crypto.randomUUID());
  useEffect(() => { void (async () => { try { const payload = await getPublicClass(token); if (!payload) throw new Error("Ссылка недействительна или срок её действия истёк"); setData(payload); } catch (reason) { setError(humanError(reason)); } finally { setLoading(false); } })(); }, [token]);
  const child = data?.children.find((item) => item.id === childId); const total = useMemo(() => data?.catalog.filter((item) => selected.includes(item.id)).reduce((sum, item) => sum + Number(item.price), 0) || 0, [data, selected]);
  function toggle(id: string) { setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); }
  async function submit() { if (!childId || !selected.length || pending) return; setPending(true); setError(""); try { const order = await submitPublicOrder({ token, childId, itemIds: selected, requestKey: requestKey.current, note: "" }); setResult(order); setStep("done"); } catch (reason) { setError(humanError(reason)); } finally { setPending(false); } }
  if (loading) return <main className="public-page"><Loader label="Открываем класс…"/></main>;
  if (error && !data) return <main className="public-page"><section className="public-error"><div className="error-illustration">!</div><h1>Ссылка недоступна</h1><p>{error}</p><span>Попросите учителя отправить актуальную ссылку.</span></section></main>;
  if (!data) return null;
  return <main className="public-page"><div className="public-shell"><header className="public-header"><div className="public-logo"><span className="brand-mark">VS</span><div><strong>Vakha Studio</strong><small>Школьная фотография</small></div></div><span className="step-indicator">{step === "child" ? "Шаг 1 из 2" : step === "services" ? "Шаг 2 из 2" : "Готово"}</span></header>
    {step === "child" && <section className="public-content"><span className="eyebrow">{data.school.name} · {data.class.name}</span><h1>{data.class.photo_session_name}</h1><p className="public-lead">Выберите своего ребёнка</p>{!data.children.length ? <Notice kind="info">Список детей пока не добавлен. Обратитесь к учителю.</Notice> : <div className="children-grid">{data.children.map((item, index) => <button className="child-choice" key={item.id} onClick={() => { setChildId(item.id); setStep("services"); }}><span className={`avatar avatar-${index % 3}`}><UserRound/></span><strong>{item.public_name}</strong><span>›</span></button>)}</div>}<div className="privacy-note">Показываются только сокращённые публичные имена.</div></section>}
    {step === "services" && <section className="public-content service-step"><button className="back-link bare-button" onClick={() => setStep("child")}><ArrowLeft size={18}/>Назад</button><span className="eyebrow">{data.school.name} · {data.class.name}</span><h1>{child?.public_name}</h1>{error && <Notice kind="error">{error}</Notice>}<div className="service-list">{data.catalog.map((item) => { const active = selected.includes(item.id); return <button className={`service-choice ${active ? "selected" : ""}`} key={item.id} onClick={() => toggle(item.id)}><div className="service-thumb">{item.preview_video_url ? <video muted playsInline poster={item.preview_url || undefined} src={item.preview_video_url}/> : item.preview_url ? <img src={item.preview_url} alt=""/> : <ServiceIcon type={item.type}/>}</div><div className="service-copy"><strong>{item.name}</strong><span>{item.short_description || item.description || ""}</span></div><b>{money(item.price)}</b><span className="service-check">{active && <Check size={17}/>}</span></button>; })}</div>{!data.catalog.length && <Notice kind="info">Каталог пуст.</Notice>}<div className="order-dock"><div><span>Выбрано: {selected.length}</span><strong>Итого: {money(total)}</strong></div><button className="button button-primary" disabled={!selected.length || pending} onClick={() => void submit()}>{pending && <LoaderCircle className="spin" size={18}/>}Отправить заявку</button></div></section>}
    {step === "done" && result && <section className="success-screen"><div className="success-mark"><CheckCircle2/></div><h1>{result.duplicate ? "Заявка уже была отправлена" : "Заявка отправлена"}</h1><span className="success-pill">Ваша заявка принята</span><div className="order-number">Номер заявки <strong>{result.order_number}</strong></div><div className="confirmation-card"><div><span>Ребёнок</span><strong>{result.child_name}</strong></div><div><span>Класс</span><strong>{result.class_name}</strong></div><div><span>Услуги</span><strong>{result.selected_items.map((item) => item.name).join(", ")}</strong></div><div><span>Итого</span><strong>{money(result.total_amount)}</strong></div></div><p>Спасибо! Мы сохраним прекрасные моменты детства.</p><button className="button button-primary button-wide" onClick={() => window.location.assign("about:blank")}>Готово</button></section>}
  </div></main>;
}
